// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMyPyyIcQiekUJ-gDtM9U_RiR2DCjDadM',
    appId: '1:66143272607:web:445dbb96e422dd0dadacaa',
    messagingSenderId: '66143272607',
    projectId: 'datazen-dbcf4',
    authDomain: 'datazen-dbcf4.firebaseapp.com',
    storageBucket: 'datazen-dbcf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9JRqc33ZPNt2JgwdaJ8CnpQFGOOUNHg',
    appId: '1:66143272607:android:b26d18d36bc47d2aadacaa',
    messagingSenderId: '66143272607',
    projectId: 'datazen-dbcf4',
    storageBucket: 'datazen-dbcf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc2X442MJedCdSUXR1X6lPFP_D5mtLTRQ',
    appId: '1:66143272607:ios:182fdd9de3a81e56adacaa',
    messagingSenderId: '66143272607',
    projectId: 'datazen-dbcf4',
    storageBucket: 'datazen-dbcf4.firebasestorage.app',
    iosClientId: '66143272607-lirae56d2pojm1v9snm4ods3gtuils2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.datazen',
  );
}
